// models/tools.js
const frameworksAndTools = [
  {
    id: 1,
    name: 'React',
    category: 'Frontend',
    description: 'A JavaScript library for building user interfaces.',
    explanation: 'React is component-based, allowing reusable UI building blocks.',
    useCase: 'Used for creating dynamic single-page applications.',
    languages: ['JavaScript', 'JSX'],
    officialWebsite: 'https://react.dev',
  },
  {
    id: 2,
    name: 'Angular',
    category: 'Frontend',
    description: 'A TypeScript-based open-source web application framework.',
    explanation: 'Maintained by Google, offers built-in tools and structure for large apps.',
    useCase: 'Enterprise web applications with structured architecture.',
    languages: ['TypeScript', 'HTML', 'CSS'],
    officialWebsite: 'https://angular.io',
  },
  {
    id: 3,
    name: 'Vue.js',
    category: 'Frontend',
    description: 'A progressive JavaScript framework for building UI on the web.',
    explanation: 'Simple, flexible, and integrates easily into projects.',
    useCase: 'Lightweight, interactive web UIs.',
    languages: ['JavaScript', 'HTML', 'CSS'],
    officialWebsite: 'https://vuejs.org',
  },
  {
    id: 4,
    name: 'Django',
    category: 'Backend',
    description: 'A high-level Python web framework for rapid development.',
    explanation: 'Includes ORM, authentication, and admin interface out of the box.',
    useCase: 'Full-stack web applications and APIs.',
    languages: ['Python'],
    officialWebsite: 'https://www.djangoproject.com/',
  },
  {
    id: 5,
    name: 'Spring Boot',
    category: 'Backend',
    description: 'A Java-based framework used to create microservices.',
    explanation: 'Simplifies Java app setup with embedded servers.',
    useCase: 'Enterprise-grade backend systems and APIs.',
    languages: ['Java'],
    officialWebsite: 'https://spring.io/projects/spring-boot',
  },
  {
    id: 6,
    name: 'Git',
    category: 'DevOps',
    description: 'Version control system for tracking changes in source code.',
    explanation: 'Distributed system allowing multiple developers to collaborate.',
    useCase: 'Source control and collaboration.',
    languages: [],
    officialWebsite: 'https://git-scm.com/',
  },
  {
    id: 7,
    name: 'Docker',
    category: 'DevOps',
    description: 'Platform to develop, ship, and run applications in containers.',
    explanation: 'Encapsulates apps with all dependencies into containers for consistency.',
    useCase: 'Containerization and deployment automation.',
    languages: [],
    officialWebsite: 'https://www.docker.com/',
  },
];

module.exports = frameworksAndTools;
